version: "3.3"
services:
  ros2-adapter:
    container_name: ros2-adapter
    build: .
    network_mode: host
    volumes:
      - "/var/lib/formant:/var/lib/formant"
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION}
